### ISSUE TITLE
CRUD Local

### ISSUE THREAD

**Issue by thalles-ab** [thalles-ab/wscarona#1]
será necessário a implementação de um CRUD de locais.
POST: criar e editar
GET: buscar
DELETE: excluir

Todo conteúdo irá trafegar em formato json UTF-8(já implementado).
Para acessar o usuário referente a solicitação utilize a variável userContext do BaseService.(Este usuário já é carregado através do token informado na requisição).

Para conseguir um token válido é necessário efetuar login(a implementação feita atualmente é por usuário e não por dispositivo, por tanto não utilize o usuário do amiguinho).

Guilherme:
code: 12345
password: 827ccb0eea8a706c4c34a16891f84e7b

Gabriel:
code: 54321
password: e10adc3949ba59abbe56e057f20f883e

Ex: de chamada de login. 
Com o retorno dessa chamada deve ser preenchido a propriedade Authorization do cabeçalho HTTP em cada uma das outras chamadas.

![captura de tela de 2016-03-29 21 14 00](https://cloud.githubusercontent.com/assets/5165791/14128439/5b2f18d8-f5f7-11e5-9882-49a4dcaa7608.png)

**Comment by thalles-ab** [comment]
Ex: de chamada de login. Com o retorno dessa chamada deve ser preenchido a propriedade Authorization do cabeçalho HTTP em cada uma das outras chamadas.
![captura de tela de 2016-03-29 21 14 00](https://cloud.githubusercontent.com/assets/5165791/14128021/316833d0-f5f3-11e5-9a6c-72fce708605f.png)

**Comment by GabrielMarques89** [comment]
Implementado (De maneira BEM simples.)
- Busca por id (place/{id})
- Busca por geoLocalization (place/search/{geo})
- Busca por todos os places do usuário em contexto (/place)
- Save (@Post)
- Delete (@Get - /place/delete/{id})

Problemas: 
- Delete - Qual a resposta para o caso de sucesso ... retornar 200 + O quê ?
- Delete - Qualquer usuário pode deletar qualquer lugar ? (Implementado: Pode deletar apenas os locais do usuário em contexto - Passado pelo token)
- Precisamos de uma UK para local (que não seja sua id burra - no momento, o update não funciona pois o ID não é serializado pelo json)
