### ISSUE TITLE
Update Student

### ISSUE THREAD

**Issue by thalles-ab** [thalles-ab/wscarona#2]
É necessário a implementação de um serviço para atualizar informações básicas de estudante.
Lembrando que matricula(code) e senha(password) não serão atualizados.

POST: atualizar.

Todo conteúdo irá trafegar em formato json UTF-8(já implementado).
Para acessar o usuário referente a solicitação utilize a variável userContext do BaseService.(Este usuário já é carregado através do token informado na requisição).

Para conseguir um token válido é necessário efetuar login(a implementação feita atualmente é por usuário e não por dispositivo, por tanto não utilize o usuário do amiguinho).

Guilherme:
code: 12345
password: 827ccb0eea8a706c4c34a16891f84e7b

Gabriel:
code: 54321
password: e10adc3949ba59abbe56e057f20f883e

Ex: de chamada de login. 
Com o retorno dessa chamada deve ser preenchido a propriedade Authorization do cabeçalho HTTP em cada uma das outras chamadas.

![captura de tela de 2016-03-29 21 14 00](https://cloud.githubusercontent.com/assets/5165791/14128559/48ec2eb2-f5f8-11e5-92de-40901b548d81.png)

**Comment by GabrielMarques89** [comment]
Feito.
